# Specifies the color enchants are shown depending on rarity.
# Options: black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, and white.
rarity-colors:
  common: yellow
  uncommon: blue
  rare: gold
  mythic: light_purple
enchants:
  # Specifies the location enchants are shown. Options: name, lore
  position: "name"
  # Toggles roman numerals for displaying enchantment levels
  roman-numerals: true
# Toggles forms for /ce command
forms:
  enabled: false
# What enchants to disable ENTIRELY
disabled-enchants: []
# What enchants to disable in specific worlds
per-world-disabled-enchants:
  NoJetpackWorld:
    - "jetpack"
# Whether or not an enchant damages world
world-damage:
  blaze: true
  lightning: true
  missile: true
  self-destruct: true
# Items the chicken enchant will drop. Formatted as "id:meta:count"
chicken:
  drops: ["266:0:1"]
miscellaneous:
  # Toggles PiggyCE's implementation of the vanilla feature to hold armor to equip
  armor-hold-equip: true